// DO NOT EDIT.
//
// Generated by the Swift generator plugin for the protocol buffer compiler.
// Source: SignalService.proto
//
// For information on using the generated types, please see the documenation:
//   https://github.com/apple/swift-protobuf/

// *
// Copyright (C) 2014-2016 Open Whisper Systems
//
// Licensed according to the LICENSE file in this repository.

import Foundation
import SwiftProtobuf

// If the compiler emits an error on this type, it is because this file
// was generated by a version of the `protoc` Swift plug-in that is
// incompatible with the version of SwiftProtobuf to which you are linking.
// Please ensure that your are building against the same version of the API
// that was used to generate this file.
fileprivate struct _GeneratedWithProtocGenSwiftVersion: SwiftProtobuf.ProtobufAPIVersionCheck {
    struct _2: SwiftProtobuf.ProtobufAPIVersion_2 {}
    typealias Version = _2
}

struct Signalservice_Envelope {
    // SwiftProtobuf.Message conformance is added in an extension below. See the
    // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
    // methods supported on all messages.

    var type: Signalservice_Envelope.TypeEnum {
        get { return self._type ?? .unknown }
        set { self._type = newValue }
    }
    /// Returns true if `type` has been explicitly set.
    var hasType: Bool { return self._type != nil }
    /// Clears the value of `type`. Subsequent reads from it will return its default value.
    mutating func clearType() { self._type = nil }

    var source: String {
        get { return self._source ?? String() }
        set { self._source = newValue }
    }
    /// Returns true if `source` has been explicitly set.
    var hasSource: Bool { return self._source != nil }
    /// Clears the value of `source`. Subsequent reads from it will return its default value.
    mutating func clearSource() { self._source = nil }

    var sourceDevice: UInt32 {
        get { return self._sourceDevice ?? 0 }
        set { self._sourceDevice = newValue }
    }
    /// Returns true if `sourceDevice` has been explicitly set.
    var hasSourceDevice: Bool { return self._sourceDevice != nil }
    /// Clears the value of `sourceDevice`. Subsequent reads from it will return its default value.
    mutating func clearSourceDevice() { self._sourceDevice = nil }

    var relay: String {
        get { return self._relay ?? String() }
        set { self._relay = newValue }
    }
    /// Returns true if `relay` has been explicitly set.
    var hasRelay: Bool { return self._relay != nil }
    /// Clears the value of `relay`. Subsequent reads from it will return its default value.
    mutating func clearRelay() { self._relay = nil }

    var timestamp: UInt64 {
        get { return self._timestamp ?? 0 }
        set { self._timestamp = newValue }
    }
    /// Returns true if `timestamp` has been explicitly set.
    var hasTimestamp: Bool { return self._timestamp != nil }
    /// Clears the value of `timestamp`. Subsequent reads from it will return its default value.
    mutating func clearTimestamp() { self._timestamp = nil }

    /// Contains an encrypted DataMessage
    var legacyMessage: Data {
        get { return self._legacyMessage ?? SwiftProtobuf.Internal.emptyData }
        set { self._legacyMessage = newValue }
    }
    /// Returns true if `legacyMessage` has been explicitly set.
    var hasLegacyMessage: Bool { return self._legacyMessage != nil }
    /// Clears the value of `legacyMessage`. Subsequent reads from it will return its default value.
    mutating func clearLegacyMessage() { self._legacyMessage = nil }

    /// Contains an encrypted Content
    var content: Data {
        get { return self._content ?? SwiftProtobuf.Internal.emptyData }
        set { self._content = newValue }
    }
    /// Returns true if `content` has been explicitly set.
    var hasContent: Bool { return self._content != nil }
    /// Clears the value of `content`. Subsequent reads from it will return its default value.
    mutating func clearContent() { self._content = nil }

    var unknownFields = SwiftProtobuf.UnknownStorage()

    enum TypeEnum: SwiftProtobuf.Enum {
        typealias RawValue = Int
        case unknown // = 0
        case ciphertext // = 1
        case keyExchange // = 2
        case prekeyBundle // = 3
        case receipt // = 5

        init() {
            self = .unknown
        }

        init?(rawValue: Int) {
            switch rawValue {
            case 0: self = .unknown
            case 1: self = .ciphertext
            case 2: self = .keyExchange
            case 3: self = .prekeyBundle
            case 5: self = .receipt
            default: return nil
            }
        }

        var rawValue: Int {
            switch self {
            case .unknown: return 0
            case .ciphertext: return 1
            case .keyExchange: return 2
            case .prekeyBundle: return 3
            case .receipt: return 5
            }
        }
    }

    init() {}

    fileprivate var _type: Signalservice_Envelope.TypeEnum?
    fileprivate var _source: String?
    fileprivate var _sourceDevice: UInt32?
    fileprivate var _relay: String?
    fileprivate var _timestamp: UInt64?
    fileprivate var _legacyMessage: Data?
    fileprivate var _content: Data?
}

struct Signalservice_Content {
    // SwiftProtobuf.Message conformance is added in an extension below. See the
    // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
    // methods supported on all messages.

    var dataMessage: Signalservice_DataMessage {
        get { return self._storage._dataMessage ?? Signalservice_DataMessage() }
        set { _uniqueStorage()._dataMessage = newValue }
    }
    /// Returns true if `dataMessage` has been explicitly set.
    var hasDataMessage: Bool { return _storage._dataMessage != nil }
    /// Clears the value of `dataMessage`. Subsequent reads from it will return its default value.
    mutating func clearDataMessage() { self._storage._dataMessage = nil }

    var syncMessage: Signalservice_SyncMessage {
        get { return self._storage._syncMessage ?? Signalservice_SyncMessage() }
        set { _uniqueStorage()._syncMessage = newValue }
    }
    /// Returns true if `syncMessage` has been explicitly set.
    var hasSyncMessage: Bool { return _storage._syncMessage != nil }
    /// Clears the value of `syncMessage`. Subsequent reads from it will return its default value.
    mutating func clearSyncMessage() { self._storage._syncMessage = nil }

    var callMessage: Signalservice_CallMessage {
        get { return self._storage._callMessage ?? Signalservice_CallMessage() }
        set { _uniqueStorage()._callMessage = newValue }
    }
    /// Returns true if `callMessage` has been explicitly set.
    var hasCallMessage: Bool { return _storage._callMessage != nil }
    /// Clears the value of `callMessage`. Subsequent reads from it will return its default value.
    mutating func clearCallMessage() { self._storage._callMessage = nil }

    var unknownFields = SwiftProtobuf.UnknownStorage()

    init() {}

    fileprivate var _storage = _StorageClass.defaultInstance
}

struct Signalservice_CallMessage {
    // SwiftProtobuf.Message conformance is added in an extension below. See the
    // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
    // methods supported on all messages.

    var offer: Signalservice_CallMessage.Offer {
        get { return self._storage._offer ?? Signalservice_CallMessage.Offer() }
        set { _uniqueStorage()._offer = newValue }
    }
    /// Returns true if `offer` has been explicitly set.
    var hasOffer: Bool { return _storage._offer != nil }
    /// Clears the value of `offer`. Subsequent reads from it will return its default value.
    mutating func clearOffer() { self._storage._offer = nil }

    var answer: Signalservice_CallMessage.Answer {
        get { return self._storage._answer ?? Signalservice_CallMessage.Answer() }
        set { _uniqueStorage()._answer = newValue }
    }
    /// Returns true if `answer` has been explicitly set.
    var hasAnswer: Bool { return _storage._answer != nil }
    /// Clears the value of `answer`. Subsequent reads from it will return its default value.
    mutating func clearAnswer() { self._storage._answer = nil }

    var iceUpdate: [Signalservice_CallMessage.IceUpdate] {
        get { return self._storage._iceUpdate }
        set { _uniqueStorage()._iceUpdate = newValue }
    }

    var hangup: Signalservice_CallMessage.Hangup {
        get { return self._storage._hangup ?? Signalservice_CallMessage.Hangup() }
        set { _uniqueStorage()._hangup = newValue }
    }
    /// Returns true if `hangup` has been explicitly set.
    var hasHangup: Bool { return _storage._hangup != nil }
    /// Clears the value of `hangup`. Subsequent reads from it will return its default value.
    mutating func clearHangup() { self._storage._hangup = nil }

    var busy: Signalservice_CallMessage.Busy {
        get { return self._storage._busy ?? Signalservice_CallMessage.Busy() }
        set { _uniqueStorage()._busy = newValue }
    }
    /// Returns true if `busy` has been explicitly set.
    var hasBusy: Bool { return _storage._busy != nil }
    /// Clears the value of `busy`. Subsequent reads from it will return its default value.
    mutating func clearBusy() { self._storage._busy = nil }

    var unknownFields = SwiftProtobuf.UnknownStorage()

    struct Offer {
        // SwiftProtobuf.Message conformance is added in an extension below. See the
        // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
        // methods supported on all messages.

        var id: UInt64 {
            get { return self._id ?? 0 }
            set { self._id = newValue }
        }
        /// Returns true if `id` has been explicitly set.
        var hasID: Bool { return self._id != nil }
        /// Clears the value of `id`. Subsequent reads from it will return its default value.
        mutating func clearID() { self._id = nil }

        var description_p: String {
            get { return self._description_p ?? String() }
            set { self._description_p = newValue }
        }
        /// Returns true if `description_p` has been explicitly set.
        var hasDescription_p: Bool { return self._description_p != nil }
        /// Clears the value of `description_p`. Subsequent reads from it will return its default value.
        mutating func clearDescription_p() { self._description_p = nil }

        var unknownFields = SwiftProtobuf.UnknownStorage()

        init() {}

        fileprivate var _id: UInt64?
        fileprivate var _description_p: String?
    }

    struct Answer {
        // SwiftProtobuf.Message conformance is added in an extension below. See the
        // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
        // methods supported on all messages.

        var id: UInt64 {
            get { return self._id ?? 0 }
            set { self._id = newValue }
        }
        /// Returns true if `id` has been explicitly set.
        var hasID: Bool { return self._id != nil }
        /// Clears the value of `id`. Subsequent reads from it will return its default value.
        mutating func clearID() { self._id = nil }

        var description_p: String {
            get { return self._description_p ?? String() }
            set { self._description_p = newValue }
        }
        /// Returns true if `description_p` has been explicitly set.
        var hasDescription_p: Bool { return self._description_p != nil }
        /// Clears the value of `description_p`. Subsequent reads from it will return its default value.
        mutating func clearDescription_p() { self._description_p = nil }

        var unknownFields = SwiftProtobuf.UnknownStorage()

        init() {}

        fileprivate var _id: UInt64?
        fileprivate var _description_p: String?
    }

    struct IceUpdate {
        // SwiftProtobuf.Message conformance is added in an extension below. See the
        // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
        // methods supported on all messages.

        var id: UInt64 {
            get { return self._id ?? 0 }
            set { self._id = newValue }
        }
        /// Returns true if `id` has been explicitly set.
        var hasID: Bool { return self._id != nil }
        /// Clears the value of `id`. Subsequent reads from it will return its default value.
        mutating func clearID() { self._id = nil }

        var sdpMid: String {
            get { return self._sdpMid ?? String() }
            set { self._sdpMid = newValue }
        }
        /// Returns true if `sdpMid` has been explicitly set.
        var hasSdpMid: Bool { return self._sdpMid != nil }
        /// Clears the value of `sdpMid`. Subsequent reads from it will return its default value.
        mutating func clearSdpMid() { self._sdpMid = nil }

        var sdpMlineIndex: UInt32 {
            get { return self._sdpMlineIndex ?? 0 }
            set { self._sdpMlineIndex = newValue }
        }
        /// Returns true if `sdpMlineIndex` has been explicitly set.
        var hasSdpMlineIndex: Bool { return self._sdpMlineIndex != nil }
        /// Clears the value of `sdpMlineIndex`. Subsequent reads from it will return its default value.
        mutating func clearSdpMlineIndex() { self._sdpMlineIndex = nil }

        var sdp: String {
            get { return self._sdp ?? String() }
            set { self._sdp = newValue }
        }
        /// Returns true if `sdp` has been explicitly set.
        var hasSdp: Bool { return self._sdp != nil }
        /// Clears the value of `sdp`. Subsequent reads from it will return its default value.
        mutating func clearSdp() { self._sdp = nil }

        var unknownFields = SwiftProtobuf.UnknownStorage()

        init() {}

        fileprivate var _id: UInt64?
        fileprivate var _sdpMid: String?
        fileprivate var _sdpMlineIndex: UInt32?
        fileprivate var _sdp: String?
    }

    struct Busy {
        // SwiftProtobuf.Message conformance is added in an extension below. See the
        // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
        // methods supported on all messages.

        var id: UInt64 {
            get { return self._id ?? 0 }
            set { self._id = newValue }
        }
        /// Returns true if `id` has been explicitly set.
        var hasID: Bool { return self._id != nil }
        /// Clears the value of `id`. Subsequent reads from it will return its default value.
        mutating func clearID() { self._id = nil }

        var unknownFields = SwiftProtobuf.UnknownStorage()

        init() {}

        fileprivate var _id: UInt64?
    }

    struct Hangup {
        // SwiftProtobuf.Message conformance is added in an extension below. See the
        // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
        // methods supported on all messages.

        var id: UInt64 {
            get { return self._id ?? 0 }
            set { self._id = newValue }
        }
        /// Returns true if `id` has been explicitly set.
        var hasID: Bool { return self._id != nil }
        /// Clears the value of `id`. Subsequent reads from it will return its default value.
        mutating func clearID() { self._id = nil }

        var unknownFields = SwiftProtobuf.UnknownStorage()

        init() {}

        fileprivate var _id: UInt64?
    }

    init() {}

    fileprivate var _storage = _StorageClass.defaultInstance
}

struct Signalservice_DataMessage {
    // SwiftProtobuf.Message conformance is added in an extension below. See the
    // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
    // methods supported on all messages.

    var body: String {
        get { return self._storage._body ?? String() }
        set { _uniqueStorage()._body = newValue }
    }
    /// Returns true if `body` has been explicitly set.
    var hasBody: Bool { return _storage._body != nil }
    /// Clears the value of `body`. Subsequent reads from it will return its default value.
    mutating func clearBody() { self._storage._body = nil }

    var attachments: [Signalservice_AttachmentPointer] {
        get { return self._storage._attachments }
        set { _uniqueStorage()._attachments = newValue }
    }

    var group: Signalservice_GroupContext {
        get { return self._storage._group ?? Signalservice_GroupContext() }
        set { _uniqueStorage()._group = newValue }
    }
    /// Returns true if `group` has been explicitly set.
    var hasGroup: Bool { return _storage._group != nil }
    /// Clears the value of `group`. Subsequent reads from it will return its default value.
    mutating func clearGroup() { self._storage._group = nil }

    var flags: UInt32 {
        get { return self._storage._flags ?? 0 }
        set { _uniqueStorage()._flags = newValue }
    }
    /// Returns true if `flags` has been explicitly set.
    var hasFlags: Bool { return _storage._flags != nil }
    /// Clears the value of `flags`. Subsequent reads from it will return its default value.
    mutating func clearFlags() { self._storage._flags = nil }

    var expireTimer: UInt32 {
        get { return self._storage._expireTimer ?? 0 }
        set { _uniqueStorage()._expireTimer = newValue }
    }
    /// Returns true if `expireTimer` has been explicitly set.
    var hasExpireTimer: Bool { return _storage._expireTimer != nil }
    /// Clears the value of `expireTimer`. Subsequent reads from it will return its default value.
    mutating func clearExpireTimer() { self._storage._expireTimer = nil }

    var unknownFields = SwiftProtobuf.UnknownStorage()

    enum Flags: SwiftProtobuf.Enum {
        typealias RawValue = Int
        case endSession // = 1
        case expirationTimerUpdate // = 2

        init() {
            self = .endSession
        }

        init?(rawValue: Int) {
            switch rawValue {
            case 1: self = .endSession
            case 2: self = .expirationTimerUpdate
            default: return nil
            }
        }

        var rawValue: Int {
            switch self {
            case .endSession: return 1
            case .expirationTimerUpdate: return 2
            }
        }
    }

    init() {}

    fileprivate var _storage = _StorageClass.defaultInstance
}

struct Signalservice_SyncMessage {
    // SwiftProtobuf.Message conformance is added in an extension below. See the
    // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
    // methods supported on all messages.

    var sent: Signalservice_SyncMessage.Sent {
        get { return self._storage._sent ?? Signalservice_SyncMessage.Sent() }
        set { _uniqueStorage()._sent = newValue }
    }
    /// Returns true if `sent` has been explicitly set.
    var hasSent: Bool { return _storage._sent != nil }
    /// Clears the value of `sent`. Subsequent reads from it will return its default value.
    mutating func clearSent() { self._storage._sent = nil }

    var contacts: Signalservice_SyncMessage.Contacts {
        get { return self._storage._contacts ?? Signalservice_SyncMessage.Contacts() }
        set { _uniqueStorage()._contacts = newValue }
    }
    /// Returns true if `contacts` has been explicitly set.
    var hasContacts: Bool { return _storage._contacts != nil }
    /// Clears the value of `contacts`. Subsequent reads from it will return its default value.
    mutating func clearContacts() { self._storage._contacts = nil }

    var groups: Signalservice_SyncMessage.Groups {
        get { return self._storage._groups ?? Signalservice_SyncMessage.Groups() }
        set { _uniqueStorage()._groups = newValue }
    }
    /// Returns true if `groups` has been explicitly set.
    var hasGroups: Bool { return _storage._groups != nil }
    /// Clears the value of `groups`. Subsequent reads from it will return its default value.
    mutating func clearGroups() { self._storage._groups = nil }

    var request: Signalservice_SyncMessage.Request {
        get { return self._storage._request ?? Signalservice_SyncMessage.Request() }
        set { _uniqueStorage()._request = newValue }
    }
    /// Returns true if `request` has been explicitly set.
    var hasRequest: Bool { return _storage._request != nil }
    /// Clears the value of `request`. Subsequent reads from it will return its default value.
    mutating func clearRequest() { self._storage._request = nil }

    var read: [Signalservice_SyncMessage.Read] {
        get { return self._storage._read }
        set { _uniqueStorage()._read = newValue }
    }

    var blocked: Signalservice_SyncMessage.Blocked {
        get { return self._storage._blocked ?? Signalservice_SyncMessage.Blocked() }
        set { _uniqueStorage()._blocked = newValue }
    }
    /// Returns true if `blocked` has been explicitly set.
    var hasBlocked: Bool { return _storage._blocked != nil }
    /// Clears the value of `blocked`. Subsequent reads from it will return its default value.
    mutating func clearBlocked() { self._storage._blocked = nil }

    var unknownFields = SwiftProtobuf.UnknownStorage()

    struct Sent {
        // SwiftProtobuf.Message conformance is added in an extension below. See the
        // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
        // methods supported on all messages.

        var destination: String {
            get { return self._storage._destination ?? String() }
            set { _uniqueStorage()._destination = newValue }
        }
        /// Returns true if `destination` has been explicitly set.
        var hasDestination: Bool { return _storage._destination != nil }
        /// Clears the value of `destination`. Subsequent reads from it will return its default value.
        mutating func clearDestination() { self._storage._destination = nil }

        var timestamp: UInt64 {
            get { return self._storage._timestamp ?? 0 }
            set { _uniqueStorage()._timestamp = newValue }
        }
        /// Returns true if `timestamp` has been explicitly set.
        var hasTimestamp: Bool { return _storage._timestamp != nil }
        /// Clears the value of `timestamp`. Subsequent reads from it will return its default value.
        mutating func clearTimestamp() { self._storage._timestamp = nil }

        var message: Signalservice_DataMessage {
            get { return self._storage._message ?? Signalservice_DataMessage() }
            set { _uniqueStorage()._message = newValue }
        }
        /// Returns true if `message` has been explicitly set.
        var hasMessage: Bool { return _storage._message != nil }
        /// Clears the value of `message`. Subsequent reads from it will return its default value.
        mutating func clearMessage() { self._storage._message = nil }

        var expirationStartTimestamp: UInt64 {
            get { return self._storage._expirationStartTimestamp ?? 0 }
            set { _uniqueStorage()._expirationStartTimestamp = newValue }
        }
        /// Returns true if `expirationStartTimestamp` has been explicitly set.
        var hasExpirationStartTimestamp: Bool { return _storage._expirationStartTimestamp != nil }
        /// Clears the value of `expirationStartTimestamp`. Subsequent reads from it will return its default value.
        mutating func clearExpirationStartTimestamp() { self._storage._expirationStartTimestamp = nil }

        var unknownFields = SwiftProtobuf.UnknownStorage()

        init() {}

        fileprivate var _storage = _StorageClass.defaultInstance
    }

    struct Contacts {
        // SwiftProtobuf.Message conformance is added in an extension below. See the
        // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
        // methods supported on all messages.

        var blob: Signalservice_AttachmentPointer {
            get { return self._storage._blob ?? Signalservice_AttachmentPointer() }
            set { _uniqueStorage()._blob = newValue }
        }
        /// Returns true if `blob` has been explicitly set.
        var hasBlob: Bool { return _storage._blob != nil }
        /// Clears the value of `blob`. Subsequent reads from it will return its default value.
        mutating func clearBlob() { self._storage._blob = nil }

        var unknownFields = SwiftProtobuf.UnknownStorage()

        init() {}

        fileprivate var _storage = _StorageClass.defaultInstance
    }

    struct Groups {
        // SwiftProtobuf.Message conformance is added in an extension below. See the
        // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
        // methods supported on all messages.

        var blob: Signalservice_AttachmentPointer {
            get { return self._storage._blob ?? Signalservice_AttachmentPointer() }
            set { _uniqueStorage()._blob = newValue }
        }
        /// Returns true if `blob` has been explicitly set.
        var hasBlob: Bool { return _storage._blob != nil }
        /// Clears the value of `blob`. Subsequent reads from it will return its default value.
        mutating func clearBlob() { self._storage._blob = nil }

        var unknownFields = SwiftProtobuf.UnknownStorage()

        init() {}

        fileprivate var _storage = _StorageClass.defaultInstance
    }

    struct Blocked {
        // SwiftProtobuf.Message conformance is added in an extension below. See the
        // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
        // methods supported on all messages.

        var numbers: [String] = []

        var unknownFields = SwiftProtobuf.UnknownStorage()

        init() {}
    }

    struct Request {
        // SwiftProtobuf.Message conformance is added in an extension below. See the
        // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
        // methods supported on all messages.

        var type: Signalservice_SyncMessage.Request.TypeEnum {
            get { return self._type ?? .unknown }
            set { self._type = newValue }
        }
        /// Returns true if `type` has been explicitly set.
        var hasType: Bool { return self._type != nil }
        /// Clears the value of `type`. Subsequent reads from it will return its default value.
        mutating func clearType() { self._type = nil }

        var unknownFields = SwiftProtobuf.UnknownStorage()

        enum TypeEnum: SwiftProtobuf.Enum {
            typealias RawValue = Int
            case unknown // = 0
            case contacts // = 1
            case groups // = 2
            case blocked // = 3

            init() {
                self = .unknown
            }

            init?(rawValue: Int) {
                switch rawValue {
                case 0: self = .unknown
                case 1: self = .contacts
                case 2: self = .groups
                case 3: self = .blocked
                default: return nil
                }
            }

            var rawValue: Int {
                switch self {
                case .unknown: return 0
                case .contacts: return 1
                case .groups: return 2
                case .blocked: return 3
                }
            }
        }

        init() {}

        fileprivate var _type: Signalservice_SyncMessage.Request.TypeEnum?
    }

    struct Read {
        // SwiftProtobuf.Message conformance is added in an extension below. See the
        // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
        // methods supported on all messages.

        var sender: String {
            get { return self._sender ?? String() }
            set { self._sender = newValue }
        }
        /// Returns true if `sender` has been explicitly set.
        var hasSender: Bool { return self._sender != nil }
        /// Clears the value of `sender`. Subsequent reads from it will return its default value.
        mutating func clearSender() { self._sender = nil }

        var timestamp: UInt64 {
            get { return self._timestamp ?? 0 }
            set { self._timestamp = newValue }
        }
        /// Returns true if `timestamp` has been explicitly set.
        var hasTimestamp: Bool { return self._timestamp != nil }
        /// Clears the value of `timestamp`. Subsequent reads from it will return its default value.
        mutating func clearTimestamp() { self._timestamp = nil }

        var unknownFields = SwiftProtobuf.UnknownStorage()

        init() {}

        fileprivate var _sender: String?
        fileprivate var _timestamp: UInt64?
    }

    init() {}

    fileprivate var _storage = _StorageClass.defaultInstance
}

struct Signalservice_AttachmentPointer {
    // SwiftProtobuf.Message conformance is added in an extension below. See the
    // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
    // methods supported on all messages.

    var id: UInt64 {
        get { return self._id ?? 0 }
        set { self._id = newValue }
    }
    /// Returns true if `id` has been explicitly set.
    var hasID: Bool { return self._id != nil }
    /// Clears the value of `id`. Subsequent reads from it will return its default value.
    mutating func clearID() { self._id = nil }

    var contentType: String {
        get { return self._contentType ?? String() }
        set { self._contentType = newValue }
    }
    /// Returns true if `contentType` has been explicitly set.
    var hasContentType: Bool { return self._contentType != nil }
    /// Clears the value of `contentType`. Subsequent reads from it will return its default value.
    mutating func clearContentType() { self._contentType = nil }

    var key: Data {
        get { return self._key ?? SwiftProtobuf.Internal.emptyData }
        set { self._key = newValue }
    }
    /// Returns true if `key` has been explicitly set.
    var hasKey: Bool { return self._key != nil }
    /// Clears the value of `key`. Subsequent reads from it will return its default value.
    mutating func clearKey() { self._key = nil }

    var size: UInt32 {
        get { return self._size ?? 0 }
        set { self._size = newValue }
    }
    /// Returns true if `size` has been explicitly set.
    var hasSize: Bool { return self._size != nil }
    /// Clears the value of `size`. Subsequent reads from it will return its default value.
    mutating func clearSize() { self._size = nil }

    var thumbnail: Data {
        get { return self._thumbnail ?? SwiftProtobuf.Internal.emptyData }
        set { self._thumbnail = newValue }
    }
    /// Returns true if `thumbnail` has been explicitly set.
    var hasThumbnail: Bool { return self._thumbnail != nil }
    /// Clears the value of `thumbnail`. Subsequent reads from it will return its default value.
    mutating func clearThumbnail() { self._thumbnail = nil }

    var digest: Data {
        get { return self._digest ?? SwiftProtobuf.Internal.emptyData }
        set { self._digest = newValue }
    }
    /// Returns true if `digest` has been explicitly set.
    var hasDigest: Bool { return self._digest != nil }
    /// Clears the value of `digest`. Subsequent reads from it will return its default value.
    mutating func clearDigest() { self._digest = nil }

    var unknownFields = SwiftProtobuf.UnknownStorage()

    init() {}

    fileprivate var _id: UInt64?
    fileprivate var _contentType: String?
    fileprivate var _key: Data?
    fileprivate var _size: UInt32?
    fileprivate var _thumbnail: Data?
    fileprivate var _digest: Data?
}

struct Signalservice_GroupContext {
    // SwiftProtobuf.Message conformance is added in an extension below. See the
    // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
    // methods supported on all messages.

    var id: Data {
        get { return self._storage._id ?? SwiftProtobuf.Internal.emptyData }
        set { _uniqueStorage()._id = newValue }
    }
    /// Returns true if `id` has been explicitly set.
    var hasID: Bool { return _storage._id != nil }
    /// Clears the value of `id`. Subsequent reads from it will return its default value.
    mutating func clearID() { self._storage._id = nil }

    var type: Signalservice_GroupContext.TypeEnum {
        get { return self._storage._type ?? .unknown }
        set { _uniqueStorage()._type = newValue }
    }
    /// Returns true if `type` has been explicitly set.
    var hasType: Bool { return _storage._type != nil }
    /// Clears the value of `type`. Subsequent reads from it will return its default value.
    mutating func clearType() { self._storage._type = nil }

    var name: String {
        get { return self._storage._name ?? String() }
        set { _uniqueStorage()._name = newValue }
    }
    /// Returns true if `name` has been explicitly set.
    var hasName: Bool { return _storage._name != nil }
    /// Clears the value of `name`. Subsequent reads from it will return its default value.
    mutating func clearName() { self._storage._name = nil }

    var members: [String] {
        get { return self._storage._members }
        set { _uniqueStorage()._members = newValue }
    }

    var avatar: Signalservice_AttachmentPointer {
        get { return self._storage._avatar ?? Signalservice_AttachmentPointer() }
        set { _uniqueStorage()._avatar = newValue }
    }
    /// Returns true if `avatar` has been explicitly set.
    var hasAvatar: Bool { return _storage._avatar != nil }
    /// Clears the value of `avatar`. Subsequent reads from it will return its default value.
    mutating func clearAvatar() { self._storage._avatar = nil }

    var unknownFields = SwiftProtobuf.UnknownStorage()

    enum TypeEnum: SwiftProtobuf.Enum {
        typealias RawValue = Int
        case unknown // = 0
        case update // = 1
        case deliver // = 2
        case quit // = 3
        case requestInfo // = 4

        init() {
            self = .unknown
        }

        init?(rawValue: Int) {
            switch rawValue {
            case 0: self = .unknown
            case 1: self = .update
            case 2: self = .deliver
            case 3: self = .quit
            case 4: self = .requestInfo
            default: return nil
            }
        }

        var rawValue: Int {
            switch self {
            case .unknown: return 0
            case .update: return 1
            case .deliver: return 2
            case .quit: return 3
            case .requestInfo: return 4
            }
        }
    }

    init() {}

    fileprivate var _storage = _StorageClass.defaultInstance
}

struct Signalservice_ContactDetails {
    // SwiftProtobuf.Message conformance is added in an extension below. See the
    // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
    // methods supported on all messages.

    var number: String {
        get { return self._storage._number ?? String() }
        set { _uniqueStorage()._number = newValue }
    }
    /// Returns true if `number` has been explicitly set.
    var hasNumber: Bool { return _storage._number != nil }
    /// Clears the value of `number`. Subsequent reads from it will return its default value.
    mutating func clearNumber() { self._storage._number = nil }

    var name: String {
        get { return self._storage._name ?? String() }
        set { _uniqueStorage()._name = newValue }
    }
    /// Returns true if `name` has been explicitly set.
    var hasName: Bool { return _storage._name != nil }
    /// Clears the value of `name`. Subsequent reads from it will return its default value.
    mutating func clearName() { self._storage._name = nil }

    var avatar: Signalservice_ContactDetails.Avatar {
        get { return self._storage._avatar ?? Signalservice_ContactDetails.Avatar() }
        set { _uniqueStorage()._avatar = newValue }
    }
    /// Returns true if `avatar` has been explicitly set.
    var hasAvatar: Bool { return _storage._avatar != nil }
    /// Clears the value of `avatar`. Subsequent reads from it will return its default value.
    mutating func clearAvatar() { self._storage._avatar = nil }

    var color: String {
        get { return self._storage._color ?? String() }
        set { _uniqueStorage()._color = newValue }
    }
    /// Returns true if `color` has been explicitly set.
    var hasColor: Bool { return _storage._color != nil }
    /// Clears the value of `color`. Subsequent reads from it will return its default value.
    mutating func clearColor() { self._storage._color = nil }

    var unknownFields = SwiftProtobuf.UnknownStorage()

    struct Avatar {
        // SwiftProtobuf.Message conformance is added in an extension below. See the
        // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
        // methods supported on all messages.

        var contentType: String {
            get { return self._contentType ?? String() }
            set { self._contentType = newValue }
        }
        /// Returns true if `contentType` has been explicitly set.
        var hasContentType: Bool { return self._contentType != nil }
        /// Clears the value of `contentType`. Subsequent reads from it will return its default value.
        mutating func clearContentType() { self._contentType = nil }

        var length: UInt32 {
            get { return self._length ?? 0 }
            set { self._length = newValue }
        }
        /// Returns true if `length` has been explicitly set.
        var hasLength: Bool { return self._length != nil }
        /// Clears the value of `length`. Subsequent reads from it will return its default value.
        mutating func clearLength() { self._length = nil }

        var unknownFields = SwiftProtobuf.UnknownStorage()

        init() {}

        fileprivate var _contentType: String?
        fileprivate var _length: UInt32?
    }

    init() {}

    fileprivate var _storage = _StorageClass.defaultInstance
}

struct Signalservice_GroupDetails {
    // SwiftProtobuf.Message conformance is added in an extension below. See the
    // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
    // methods supported on all messages.

    var id: Data {
        get { return self._storage._id ?? SwiftProtobuf.Internal.emptyData }
        set { _uniqueStorage()._id = newValue }
    }
    /// Returns true if `id` has been explicitly set.
    var hasID: Bool { return _storage._id != nil }
    /// Clears the value of `id`. Subsequent reads from it will return its default value.
    mutating func clearID() { self._storage._id = nil }

    var name: String {
        get { return self._storage._name ?? String() }
        set { _uniqueStorage()._name = newValue }
    }
    /// Returns true if `name` has been explicitly set.
    var hasName: Bool { return _storage._name != nil }
    /// Clears the value of `name`. Subsequent reads from it will return its default value.
    mutating func clearName() { self._storage._name = nil }

    var members: [String] {
        get { return self._storage._members }
        set { _uniqueStorage()._members = newValue }
    }

    var avatar: Signalservice_GroupDetails.Avatar {
        get { return self._storage._avatar ?? Signalservice_GroupDetails.Avatar() }
        set { _uniqueStorage()._avatar = newValue }
    }
    /// Returns true if `avatar` has been explicitly set.
    var hasAvatar: Bool { return _storage._avatar != nil }
    /// Clears the value of `avatar`. Subsequent reads from it will return its default value.
    mutating func clearAvatar() { self._storage._avatar = nil }

    var active: Bool {
        get { return self._storage._active ?? true }
        set { _uniqueStorage()._active = newValue }
    }
    /// Returns true if `active` has been explicitly set.
    var hasActive: Bool { return _storage._active != nil }
    /// Clears the value of `active`. Subsequent reads from it will return its default value.
    mutating func clearActive() { self._storage._active = nil }

    var unknownFields = SwiftProtobuf.UnknownStorage()

    struct Avatar {
        // SwiftProtobuf.Message conformance is added in an extension below. See the
        // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
        // methods supported on all messages.

        var contentType: String {
            get { return self._contentType ?? String() }
            set { self._contentType = newValue }
        }
        /// Returns true if `contentType` has been explicitly set.
        var hasContentType: Bool { return self._contentType != nil }
        /// Clears the value of `contentType`. Subsequent reads from it will return its default value.
        mutating func clearContentType() { self._contentType = nil }

        var length: UInt32 {
            get { return self._length ?? 0 }
            set { self._length = newValue }
        }
        /// Returns true if `length` has been explicitly set.
        var hasLength: Bool { return self._length != nil }
        /// Clears the value of `length`. Subsequent reads from it will return its default value.
        mutating func clearLength() { self._length = nil }

        var unknownFields = SwiftProtobuf.UnknownStorage()

        init() {}

        fileprivate var _contentType: String?
        fileprivate var _length: UInt32?
    }

    init() {}

    fileprivate var _storage = _StorageClass.defaultInstance
}

// MARK: - Code below here is support for the SwiftProtobuf runtime.

fileprivate let _protobuf_package = "signalservice"

extension Signalservice_Envelope: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
    static let protoMessageName: String = _protobuf_package + ".Envelope"
    static let _protobuf_nameMap: SwiftProtobuf._NameMap = [
        1: .same(proto: "type"),
        2: .same(proto: "source"),
        7: .same(proto: "sourceDevice"),
        3: .same(proto: "relay"),
        5: .same(proto: "timestamp"),
        6: .same(proto: "legacyMessage"),
        8: .same(proto: "content")
    ]

    mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
        while let fieldNumber = try decoder.nextFieldNumber() {
            switch fieldNumber {
            case 1: try decoder.decodeSingularEnumField(value: &self._type)
            case 2: try decoder.decodeSingularStringField(value: &self._source)
            case 3: try decoder.decodeSingularStringField(value: &self._relay)
            case 5: try decoder.decodeSingularUInt64Field(value: &self._timestamp)
            case 6: try decoder.decodeSingularBytesField(value: &self._legacyMessage)
            case 7: try decoder.decodeSingularUInt32Field(value: &self._sourceDevice)
            case 8: try decoder.decodeSingularBytesField(value: &self._content)
            default: break
            }
        }
    }

    func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
        if let v = self._type {
            try visitor.visitSingularEnumField(value: v, fieldNumber: 1)
        }
        if let v = self._source {
            try visitor.visitSingularStringField(value: v, fieldNumber: 2)
        }
        if let v = self._relay {
            try visitor.visitSingularStringField(value: v, fieldNumber: 3)
        }
        if let v = self._timestamp {
            try visitor.visitSingularUInt64Field(value: v, fieldNumber: 5)
        }
        if let v = self._legacyMessage {
            try visitor.visitSingularBytesField(value: v, fieldNumber: 6)
        }
        if let v = self._sourceDevice {
            try visitor.visitSingularUInt32Field(value: v, fieldNumber: 7)
        }
        if let v = self._content {
            try visitor.visitSingularBytesField(value: v, fieldNumber: 8)
        }
        try self.unknownFields.traverse(visitor: &visitor)
    }

    func _protobuf_generated_isEqualTo(other: Signalservice_Envelope) -> Bool {
        if self._type != other._type { return false }
        if self._source != other._source { return false }
        if self._sourceDevice != other._sourceDevice { return false }
        if self._relay != other._relay { return false }
        if self._timestamp != other._timestamp { return false }
        if self._legacyMessage != other._legacyMessage { return false }
        if self._content != other._content { return false }
        if self.unknownFields != other.unknownFields { return false }
        return true
    }
}

extension Signalservice_Envelope.TypeEnum: SwiftProtobuf._ProtoNameProviding {
    static let _protobuf_nameMap: SwiftProtobuf._NameMap = [
        0: .same(proto: "UNKNOWN"),
        1: .same(proto: "CIPHERTEXT"),
        2: .same(proto: "KEY_EXCHANGE"),
        3: .same(proto: "PREKEY_BUNDLE"),
        5: .same(proto: "RECEIPT")
    ]
}

extension Signalservice_Content: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
    static let protoMessageName: String = _protobuf_package + ".Content"
    static let _protobuf_nameMap: SwiftProtobuf._NameMap = [
        1: .same(proto: "dataMessage"),
        2: .same(proto: "syncMessage"),
        3: .same(proto: "callMessage")
    ]

    fileprivate class _StorageClass {
        var _dataMessage: Signalservice_DataMessage?
        var _syncMessage: Signalservice_SyncMessage?
        var _callMessage: Signalservice_CallMessage?

        static let defaultInstance = _StorageClass()

        private init() {}

        init(copying source: _StorageClass) {
            self._dataMessage = source._dataMessage
            self._syncMessage = source._syncMessage
            self._callMessage = source._callMessage
        }
    }

    fileprivate mutating func _uniqueStorage() -> _StorageClass {
        if !isKnownUniquelyReferenced(&self._storage) {
            self._storage = _StorageClass(copying: self._storage)
        }
        return self._storage
    }

    mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
        _ = self._uniqueStorage()
        try withExtendedLifetime(self._storage) { (_storage: _StorageClass) in
            while let fieldNumber = try decoder.nextFieldNumber() {
                switch fieldNumber {
                case 1: try decoder.decodeSingularMessageField(value: &_storage._dataMessage)
                case 2: try decoder.decodeSingularMessageField(value: &_storage._syncMessage)
                case 3: try decoder.decodeSingularMessageField(value: &_storage._callMessage)
                default: break
                }
            }
        }
    }

    func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
        try withExtendedLifetime(self._storage) { (_storage: _StorageClass) in
            if let v = _storage._dataMessage {
                try visitor.visitSingularMessageField(value: v, fieldNumber: 1)
            }
            if let v = _storage._syncMessage {
                try visitor.visitSingularMessageField(value: v, fieldNumber: 2)
            }
            if let v = _storage._callMessage {
                try visitor.visitSingularMessageField(value: v, fieldNumber: 3)
            }
        }
        try self.unknownFields.traverse(visitor: &visitor)
    }

    func _protobuf_generated_isEqualTo(other: Signalservice_Content) -> Bool {
        if self._storage !== other._storage {
            let storagesAreEqual: Bool = withExtendedLifetime((_storage, other._storage)) { (_args: (_StorageClass, _StorageClass)) in
                let _storage = _args.0
                let other_storage = _args.1
                if _storage._dataMessage != other_storage._dataMessage { return false }
                if _storage._syncMessage != other_storage._syncMessage { return false }
                if _storage._callMessage != other_storage._callMessage { return false }
                return true
            }
            if !storagesAreEqual { return false }
        }
        if self.unknownFields != other.unknownFields { return false }
        return true
    }
}

extension Signalservice_CallMessage: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
    static let protoMessageName: String = _protobuf_package + ".CallMessage"
    static let _protobuf_nameMap: SwiftProtobuf._NameMap = [
        1: .same(proto: "offer"),
        2: .same(proto: "answer"),
        3: .same(proto: "iceUpdate"),
        4: .same(proto: "hangup"),
        5: .same(proto: "busy")
    ]

    fileprivate class _StorageClass {
        var _offer: Signalservice_CallMessage.Offer?
        var _answer: Signalservice_CallMessage.Answer?
        var _iceUpdate: [Signalservice_CallMessage.IceUpdate] = []
        var _hangup: Signalservice_CallMessage.Hangup?
        var _busy: Signalservice_CallMessage.Busy?

        static let defaultInstance = _StorageClass()

        private init() {}

        init(copying source: _StorageClass) {
            self._offer = source._offer
            self._answer = source._answer
            self._iceUpdate = source._iceUpdate
            self._hangup = source._hangup
            self._busy = source._busy
        }
    }

    fileprivate mutating func _uniqueStorage() -> _StorageClass {
        if !isKnownUniquelyReferenced(&self._storage) {
            self._storage = _StorageClass(copying: self._storage)
        }
        return self._storage
    }

    mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
        _ = self._uniqueStorage()
        try withExtendedLifetime(self._storage) { (_storage: _StorageClass) in
            while let fieldNumber = try decoder.nextFieldNumber() {
                switch fieldNumber {
                case 1: try decoder.decodeSingularMessageField(value: &_storage._offer)
                case 2: try decoder.decodeSingularMessageField(value: &_storage._answer)
                case 3: try decoder.decodeRepeatedMessageField(value: &_storage._iceUpdate)
                case 4: try decoder.decodeSingularMessageField(value: &_storage._hangup)
                case 5: try decoder.decodeSingularMessageField(value: &_storage._busy)
                default: break
                }
            }
        }
    }

    func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
        try withExtendedLifetime(self._storage) { (_storage: _StorageClass) in
            if let v = _storage._offer {
                try visitor.visitSingularMessageField(value: v, fieldNumber: 1)
            }
            if let v = _storage._answer {
                try visitor.visitSingularMessageField(value: v, fieldNumber: 2)
            }
            if !_storage._iceUpdate.isEmpty {
                try visitor.visitRepeatedMessageField(value: _storage._iceUpdate, fieldNumber: 3)
            }
            if let v = _storage._hangup {
                try visitor.visitSingularMessageField(value: v, fieldNumber: 4)
            }
            if let v = _storage._busy {
                try visitor.visitSingularMessageField(value: v, fieldNumber: 5)
            }
        }
        try self.unknownFields.traverse(visitor: &visitor)
    }

    func _protobuf_generated_isEqualTo(other: Signalservice_CallMessage) -> Bool {
        if self._storage !== other._storage {
            let storagesAreEqual: Bool = withExtendedLifetime((_storage, other._storage)) { (_args: (_StorageClass, _StorageClass)) in
                let _storage = _args.0
                let other_storage = _args.1
                if _storage._offer != other_storage._offer { return false }
                if _storage._answer != other_storage._answer { return false }
                if _storage._iceUpdate != other_storage._iceUpdate { return false }
                if _storage._hangup != other_storage._hangup { return false }
                if _storage._busy != other_storage._busy { return false }
                return true
            }
            if !storagesAreEqual { return false }
        }
        if self.unknownFields != other.unknownFields { return false }
        return true
    }
}

extension Signalservice_CallMessage.Offer: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
    static let protoMessageName: String = Signalservice_CallMessage.protoMessageName + ".Offer"
    static let _protobuf_nameMap: SwiftProtobuf._NameMap = [
        1: .same(proto: "id"),
        2: .same(proto: "description")
    ]

    mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
        while let fieldNumber = try decoder.nextFieldNumber() {
            switch fieldNumber {
            case 1: try decoder.decodeSingularUInt64Field(value: &self._id)
            case 2: try decoder.decodeSingularStringField(value: &self._description_p)
            default: break
            }
        }
    }

    func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
        if let v = self._id {
            try visitor.visitSingularUInt64Field(value: v, fieldNumber: 1)
        }
        if let v = self._description_p {
            try visitor.visitSingularStringField(value: v, fieldNumber: 2)
        }
        try self.unknownFields.traverse(visitor: &visitor)
    }

    func _protobuf_generated_isEqualTo(other: Signalservice_CallMessage.Offer) -> Bool {
        if self._id != other._id { return false }
        if self._description_p != other._description_p { return false }
        if self.unknownFields != other.unknownFields { return false }
        return true
    }
}

extension Signalservice_CallMessage.Answer: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
    static let protoMessageName: String = Signalservice_CallMessage.protoMessageName + ".Answer"
    static let _protobuf_nameMap: SwiftProtobuf._NameMap = [
        1: .same(proto: "id"),
        2: .same(proto: "description")
    ]

    mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
        while let fieldNumber = try decoder.nextFieldNumber() {
            switch fieldNumber {
            case 1: try decoder.decodeSingularUInt64Field(value: &self._id)
            case 2: try decoder.decodeSingularStringField(value: &self._description_p)
            default: break
            }
        }
    }

    func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
        if let v = self._id {
            try visitor.visitSingularUInt64Field(value: v, fieldNumber: 1)
        }
        if let v = self._description_p {
            try visitor.visitSingularStringField(value: v, fieldNumber: 2)
        }
        try self.unknownFields.traverse(visitor: &visitor)
    }

    func _protobuf_generated_isEqualTo(other: Signalservice_CallMessage.Answer) -> Bool {
        if self._id != other._id { return false }
        if self._description_p != other._description_p { return false }
        if self.unknownFields != other.unknownFields { return false }
        return true
    }
}

extension Signalservice_CallMessage.IceUpdate: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
    static let protoMessageName: String = Signalservice_CallMessage.protoMessageName + ".IceUpdate"
    static let _protobuf_nameMap: SwiftProtobuf._NameMap = [
        1: .same(proto: "id"),
        2: .same(proto: "sdpMid"),
        3: .same(proto: "sdpMLineIndex"),
        4: .same(proto: "sdp")
    ]

    mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
        while let fieldNumber = try decoder.nextFieldNumber() {
            switch fieldNumber {
            case 1: try decoder.decodeSingularUInt64Field(value: &self._id)
            case 2: try decoder.decodeSingularStringField(value: &self._sdpMid)
            case 3: try decoder.decodeSingularUInt32Field(value: &self._sdpMlineIndex)
            case 4: try decoder.decodeSingularStringField(value: &self._sdp)
            default: break
            }
        }
    }

    func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
        if let v = self._id {
            try visitor.visitSingularUInt64Field(value: v, fieldNumber: 1)
        }
        if let v = self._sdpMid {
            try visitor.visitSingularStringField(value: v, fieldNumber: 2)
        }
        if let v = self._sdpMlineIndex {
            try visitor.visitSingularUInt32Field(value: v, fieldNumber: 3)
        }
        if let v = self._sdp {
            try visitor.visitSingularStringField(value: v, fieldNumber: 4)
        }
        try self.unknownFields.traverse(visitor: &visitor)
    }

    func _protobuf_generated_isEqualTo(other: Signalservice_CallMessage.IceUpdate) -> Bool {
        if self._id != other._id { return false }
        if self._sdpMid != other._sdpMid { return false }
        if self._sdpMlineIndex != other._sdpMlineIndex { return false }
        if self._sdp != other._sdp { return false }
        if self.unknownFields != other.unknownFields { return false }
        return true
    }
}

extension Signalservice_CallMessage.Busy: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
    static let protoMessageName: String = Signalservice_CallMessage.protoMessageName + ".Busy"
    static let _protobuf_nameMap: SwiftProtobuf._NameMap = [
        1: .same(proto: "id")
    ]

    mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
        while let fieldNumber = try decoder.nextFieldNumber() {
            switch fieldNumber {
            case 1: try decoder.decodeSingularUInt64Field(value: &self._id)
            default: break
            }
        }
    }

    func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
        if let v = self._id {
            try visitor.visitSingularUInt64Field(value: v, fieldNumber: 1)
        }
        try self.unknownFields.traverse(visitor: &visitor)
    }

    func _protobuf_generated_isEqualTo(other: Signalservice_CallMessage.Busy) -> Bool {
        if self._id != other._id { return false }
        if self.unknownFields != other.unknownFields { return false }
        return true
    }
}

extension Signalservice_CallMessage.Hangup: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
    static let protoMessageName: String = Signalservice_CallMessage.protoMessageName + ".Hangup"
    static let _protobuf_nameMap: SwiftProtobuf._NameMap = [
        1: .same(proto: "id")
    ]

    mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
        while let fieldNumber = try decoder.nextFieldNumber() {
            switch fieldNumber {
            case 1: try decoder.decodeSingularUInt64Field(value: &self._id)
            default: break
            }
        }
    }

    func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
        if let v = self._id {
            try visitor.visitSingularUInt64Field(value: v, fieldNumber: 1)
        }
        try self.unknownFields.traverse(visitor: &visitor)
    }

    func _protobuf_generated_isEqualTo(other: Signalservice_CallMessage.Hangup) -> Bool {
        if self._id != other._id { return false }
        if self.unknownFields != other.unknownFields { return false }
        return true
    }
}

extension Signalservice_DataMessage: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
    static let protoMessageName: String = _protobuf_package + ".DataMessage"
    static let _protobuf_nameMap: SwiftProtobuf._NameMap = [
        1: .same(proto: "body"),
        2: .same(proto: "attachments"),
        3: .same(proto: "group"),
        4: .same(proto: "flags"),
        5: .same(proto: "expireTimer")
    ]

    fileprivate class _StorageClass {
        var _body: String?
        var _attachments: [Signalservice_AttachmentPointer] = []
        var _group: Signalservice_GroupContext?
        var _flags: UInt32?
        var _expireTimer: UInt32?

        static let defaultInstance = _StorageClass()

        private init() {}

        init(copying source: _StorageClass) {
            self._body = source._body
            self._attachments = source._attachments
            self._group = source._group
            self._flags = source._flags
            self._expireTimer = source._expireTimer
        }
    }

    fileprivate mutating func _uniqueStorage() -> _StorageClass {
        if !isKnownUniquelyReferenced(&self._storage) {
            self._storage = _StorageClass(copying: self._storage)
        }
        return self._storage
    }

    mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
        _ = self._uniqueStorage()
        try withExtendedLifetime(self._storage) { (_storage: _StorageClass) in
            while let fieldNumber = try decoder.nextFieldNumber() {
                switch fieldNumber {
                case 1: try decoder.decodeSingularStringField(value: &_storage._body)
                case 2: try decoder.decodeRepeatedMessageField(value: &_storage._attachments)
                case 3: try decoder.decodeSingularMessageField(value: &_storage._group)
                case 4: try decoder.decodeSingularUInt32Field(value: &_storage._flags)
                case 5: try decoder.decodeSingularUInt32Field(value: &_storage._expireTimer)
                default: break
                }
            }
        }
    }

    func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
        try withExtendedLifetime(self._storage) { (_storage: _StorageClass) in
            if let v = _storage._body {
                try visitor.visitSingularStringField(value: v, fieldNumber: 1)
            }
            if !_storage._attachments.isEmpty {
                try visitor.visitRepeatedMessageField(value: _storage._attachments, fieldNumber: 2)
            }
            if let v = _storage._group {
                try visitor.visitSingularMessageField(value: v, fieldNumber: 3)
            }
            if let v = _storage._flags {
                try visitor.visitSingularUInt32Field(value: v, fieldNumber: 4)
            }
            if let v = _storage._expireTimer {
                try visitor.visitSingularUInt32Field(value: v, fieldNumber: 5)
            }
        }
        try self.unknownFields.traverse(visitor: &visitor)
    }

    func _protobuf_generated_isEqualTo(other: Signalservice_DataMessage) -> Bool {
        if self._storage !== other._storage {
            let storagesAreEqual: Bool = withExtendedLifetime((_storage, other._storage)) { (_args: (_StorageClass, _StorageClass)) in
                let _storage = _args.0
                let other_storage = _args.1
                if _storage._body != other_storage._body { return false }
                if _storage._attachments != other_storage._attachments { return false }
                if _storage._group != other_storage._group { return false }
                if _storage._flags != other_storage._flags { return false }
                if _storage._expireTimer != other_storage._expireTimer { return false }
                return true
            }
            if !storagesAreEqual { return false }
        }
        if self.unknownFields != other.unknownFields { return false }
        return true
    }
}

extension Signalservice_DataMessage.Flags: SwiftProtobuf._ProtoNameProviding {
    static let _protobuf_nameMap: SwiftProtobuf._NameMap = [
        1: .same(proto: "END_SESSION"),
        2: .same(proto: "EXPIRATION_TIMER_UPDATE")
    ]
}

extension Signalservice_SyncMessage: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
    static let protoMessageName: String = _protobuf_package + ".SyncMessage"
    static let _protobuf_nameMap: SwiftProtobuf._NameMap = [
        1: .same(proto: "sent"),
        2: .same(proto: "contacts"),
        3: .same(proto: "groups"),
        4: .same(proto: "request"),
        5: .same(proto: "read"),
        6: .same(proto: "blocked")
    ]

    fileprivate class _StorageClass {
        var _sent: Signalservice_SyncMessage.Sent?
        var _contacts: Signalservice_SyncMessage.Contacts?
        var _groups: Signalservice_SyncMessage.Groups?
        var _request: Signalservice_SyncMessage.Request?
        var _read: [Signalservice_SyncMessage.Read] = []
        var _blocked: Signalservice_SyncMessage.Blocked?

        static let defaultInstance = _StorageClass()

        private init() {}

        init(copying source: _StorageClass) {
            self._sent = source._sent
            self._contacts = source._contacts
            self._groups = source._groups
            self._request = source._request
            self._read = source._read
            self._blocked = source._blocked
        }
    }

    fileprivate mutating func _uniqueStorage() -> _StorageClass {
        if !isKnownUniquelyReferenced(&self._storage) {
            self._storage = _StorageClass(copying: self._storage)
        }
        return self._storage
    }

    mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
        _ = self._uniqueStorage()
        try withExtendedLifetime(self._storage) { (_storage: _StorageClass) in
            while let fieldNumber = try decoder.nextFieldNumber() {
                switch fieldNumber {
                case 1: try decoder.decodeSingularMessageField(value: &_storage._sent)
                case 2: try decoder.decodeSingularMessageField(value: &_storage._contacts)
                case 3: try decoder.decodeSingularMessageField(value: &_storage._groups)
                case 4: try decoder.decodeSingularMessageField(value: &_storage._request)
                case 5: try decoder.decodeRepeatedMessageField(value: &_storage._read)
                case 6: try decoder.decodeSingularMessageField(value: &_storage._blocked)
                default: break
                }
            }
        }
    }

    func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
        try withExtendedLifetime(self._storage) { (_storage: _StorageClass) in
            if let v = _storage._sent {
                try visitor.visitSingularMessageField(value: v, fieldNumber: 1)
            }
            if let v = _storage._contacts {
                try visitor.visitSingularMessageField(value: v, fieldNumber: 2)
            }
            if let v = _storage._groups {
                try visitor.visitSingularMessageField(value: v, fieldNumber: 3)
            }
            if let v = _storage._request {
                try visitor.visitSingularMessageField(value: v, fieldNumber: 4)
            }
            if !_storage._read.isEmpty {
                try visitor.visitRepeatedMessageField(value: _storage._read, fieldNumber: 5)
            }
            if let v = _storage._blocked {
                try visitor.visitSingularMessageField(value: v, fieldNumber: 6)
            }
        }
        try self.unknownFields.traverse(visitor: &visitor)
    }

    func _protobuf_generated_isEqualTo(other: Signalservice_SyncMessage) -> Bool {
        if self._storage !== other._storage {
            let storagesAreEqual: Bool = withExtendedLifetime((_storage, other._storage)) { (_args: (_StorageClass, _StorageClass)) in
                let _storage = _args.0
                let other_storage = _args.1
                if _storage._sent != other_storage._sent { return false }
                if _storage._contacts != other_storage._contacts { return false }
                if _storage._groups != other_storage._groups { return false }
                if _storage._request != other_storage._request { return false }
                if _storage._read != other_storage._read { return false }
                if _storage._blocked != other_storage._blocked { return false }
                return true
            }
            if !storagesAreEqual { return false }
        }
        if self.unknownFields != other.unknownFields { return false }
        return true
    }
}

extension Signalservice_SyncMessage.Sent: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
    static let protoMessageName: String = Signalservice_SyncMessage.protoMessageName + ".Sent"
    static let _protobuf_nameMap: SwiftProtobuf._NameMap = [
        1: .same(proto: "destination"),
        2: .same(proto: "timestamp"),
        3: .same(proto: "message"),
        4: .same(proto: "expirationStartTimestamp")
    ]

    fileprivate class _StorageClass {
        var _destination: String?
        var _timestamp: UInt64?
        var _message: Signalservice_DataMessage?
        var _expirationStartTimestamp: UInt64?

        static let defaultInstance = _StorageClass()

        private init() {}

        init(copying source: _StorageClass) {
            self._destination = source._destination
            self._timestamp = source._timestamp
            self._message = source._message
            self._expirationStartTimestamp = source._expirationStartTimestamp
        }
    }

    fileprivate mutating func _uniqueStorage() -> _StorageClass {
        if !isKnownUniquelyReferenced(&self._storage) {
            self._storage = _StorageClass(copying: self._storage)
        }
        return self._storage
    }

    mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
        _ = self._uniqueStorage()
        try withExtendedLifetime(self._storage) { (_storage: _StorageClass) in
            while let fieldNumber = try decoder.nextFieldNumber() {
                switch fieldNumber {
                case 1: try decoder.decodeSingularStringField(value: &_storage._destination)
                case 2: try decoder.decodeSingularUInt64Field(value: &_storage._timestamp)
                case 3: try decoder.decodeSingularMessageField(value: &_storage._message)
                case 4: try decoder.decodeSingularUInt64Field(value: &_storage._expirationStartTimestamp)
                default: break
                }
            }
        }
    }

    func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
        try withExtendedLifetime(self._storage) { (_storage: _StorageClass) in
            if let v = _storage._destination {
                try visitor.visitSingularStringField(value: v, fieldNumber: 1)
            }
            if let v = _storage._timestamp {
                try visitor.visitSingularUInt64Field(value: v, fieldNumber: 2)
            }
            if let v = _storage._message {
                try visitor.visitSingularMessageField(value: v, fieldNumber: 3)
            }
            if let v = _storage._expirationStartTimestamp {
                try visitor.visitSingularUInt64Field(value: v, fieldNumber: 4)
            }
        }
        try self.unknownFields.traverse(visitor: &visitor)
    }

    func _protobuf_generated_isEqualTo(other: Signalservice_SyncMessage.Sent) -> Bool {
        if self._storage !== other._storage {
            let storagesAreEqual: Bool = withExtendedLifetime((_storage, other._storage)) { (_args: (_StorageClass, _StorageClass)) in
                let _storage = _args.0
                let other_storage = _args.1
                if _storage._destination != other_storage._destination { return false }
                if _storage._timestamp != other_storage._timestamp { return false }
                if _storage._message != other_storage._message { return false }
                if _storage._expirationStartTimestamp != other_storage._expirationStartTimestamp { return false }
                return true
            }
            if !storagesAreEqual { return false }
        }
        if self.unknownFields != other.unknownFields { return false }
        return true
    }
}

extension Signalservice_SyncMessage.Contacts: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
    static let protoMessageName: String = Signalservice_SyncMessage.protoMessageName + ".Contacts"
    static let _protobuf_nameMap: SwiftProtobuf._NameMap = [
        1: .same(proto: "blob")
    ]

    fileprivate class _StorageClass {
        var _blob: Signalservice_AttachmentPointer?

        static let defaultInstance = _StorageClass()

        private init() {}

        init(copying source: _StorageClass) {
            self._blob = source._blob
        }
    }

    fileprivate mutating func _uniqueStorage() -> _StorageClass {
        if !isKnownUniquelyReferenced(&self._storage) {
            self._storage = _StorageClass(copying: self._storage)
        }
        return self._storage
    }

    mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
        _ = self._uniqueStorage()
        try withExtendedLifetime(self._storage) { (_storage: _StorageClass) in
            while let fieldNumber = try decoder.nextFieldNumber() {
                switch fieldNumber {
                case 1: try decoder.decodeSingularMessageField(value: &_storage._blob)
                default: break
                }
            }
        }
    }

    func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
        try withExtendedLifetime(self._storage) { (_storage: _StorageClass) in
            if let v = _storage._blob {
                try visitor.visitSingularMessageField(value: v, fieldNumber: 1)
            }
        }
        try self.unknownFields.traverse(visitor: &visitor)
    }

    func _protobuf_generated_isEqualTo(other: Signalservice_SyncMessage.Contacts) -> Bool {
        if self._storage !== other._storage {
            let storagesAreEqual: Bool = withExtendedLifetime((_storage, other._storage)) { (_args: (_StorageClass, _StorageClass)) in
                let _storage = _args.0
                let other_storage = _args.1
                if _storage._blob != other_storage._blob { return false }
                return true
            }
            if !storagesAreEqual { return false }
        }
        if self.unknownFields != other.unknownFields { return false }
        return true
    }
}

extension Signalservice_SyncMessage.Groups: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
    static let protoMessageName: String = Signalservice_SyncMessage.protoMessageName + ".Groups"
    static let _protobuf_nameMap: SwiftProtobuf._NameMap = [
        1: .same(proto: "blob")
    ]

    fileprivate class _StorageClass {
        var _blob: Signalservice_AttachmentPointer?

        static let defaultInstance = _StorageClass()

        private init() {}

        init(copying source: _StorageClass) {
            self._blob = source._blob
        }
    }

    fileprivate mutating func _uniqueStorage() -> _StorageClass {
        if !isKnownUniquelyReferenced(&self._storage) {
            self._storage = _StorageClass(copying: self._storage)
        }
        return self._storage
    }

    mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
        _ = self._uniqueStorage()
        try withExtendedLifetime(self._storage) { (_storage: _StorageClass) in
            while let fieldNumber = try decoder.nextFieldNumber() {
                switch fieldNumber {
                case 1: try decoder.decodeSingularMessageField(value: &_storage._blob)
                default: break
                }
            }
        }
    }

    func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
        try withExtendedLifetime(self._storage) { (_storage: _StorageClass) in
            if let v = _storage._blob {
                try visitor.visitSingularMessageField(value: v, fieldNumber: 1)
            }
        }
        try self.unknownFields.traverse(visitor: &visitor)
    }

    func _protobuf_generated_isEqualTo(other: Signalservice_SyncMessage.Groups) -> Bool {
        if self._storage !== other._storage {
            let storagesAreEqual: Bool = withExtendedLifetime((_storage, other._storage)) { (_args: (_StorageClass, _StorageClass)) in
                let _storage = _args.0
                let other_storage = _args.1
                if _storage._blob != other_storage._blob { return false }
                return true
            }
            if !storagesAreEqual { return false }
        }
        if self.unknownFields != other.unknownFields { return false }
        return true
    }
}

extension Signalservice_SyncMessage.Blocked: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
    static let protoMessageName: String = Signalservice_SyncMessage.protoMessageName + ".Blocked"
    static let _protobuf_nameMap: SwiftProtobuf._NameMap = [
        1: .same(proto: "numbers")
    ]

    mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
        while let fieldNumber = try decoder.nextFieldNumber() {
            switch fieldNumber {
            case 1: try decoder.decodeRepeatedStringField(value: &self.numbers)
            default: break
            }
        }
    }

    func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
        if !self.numbers.isEmpty {
            try visitor.visitRepeatedStringField(value: self.numbers, fieldNumber: 1)
        }
        try self.unknownFields.traverse(visitor: &visitor)
    }

    func _protobuf_generated_isEqualTo(other: Signalservice_SyncMessage.Blocked) -> Bool {
        if self.numbers != other.numbers { return false }
        if self.unknownFields != other.unknownFields { return false }
        return true
    }
}

extension Signalservice_SyncMessage.Request: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
    static let protoMessageName: String = Signalservice_SyncMessage.protoMessageName + ".Request"
    static let _protobuf_nameMap: SwiftProtobuf._NameMap = [
        1: .same(proto: "type")
    ]

    mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
        while let fieldNumber = try decoder.nextFieldNumber() {
            switch fieldNumber {
            case 1: try decoder.decodeSingularEnumField(value: &self._type)
            default: break
            }
        }
    }

    func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
        if let v = self._type {
            try visitor.visitSingularEnumField(value: v, fieldNumber: 1)
        }
        try self.unknownFields.traverse(visitor: &visitor)
    }

    func _protobuf_generated_isEqualTo(other: Signalservice_SyncMessage.Request) -> Bool {
        if self._type != other._type { return false }
        if self.unknownFields != other.unknownFields { return false }
        return true
    }
}

extension Signalservice_SyncMessage.Request.TypeEnum: SwiftProtobuf._ProtoNameProviding {
    static let _protobuf_nameMap: SwiftProtobuf._NameMap = [
        0: .same(proto: "UNKNOWN"),
        1: .same(proto: "CONTACTS"),
        2: .same(proto: "GROUPS"),
        3: .same(proto: "BLOCKED")
    ]
}

extension Signalservice_SyncMessage.Read: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
    static let protoMessageName: String = Signalservice_SyncMessage.protoMessageName + ".Read"
    static let _protobuf_nameMap: SwiftProtobuf._NameMap = [
        1: .same(proto: "sender"),
        2: .same(proto: "timestamp")
    ]

    mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
        while let fieldNumber = try decoder.nextFieldNumber() {
            switch fieldNumber {
            case 1: try decoder.decodeSingularStringField(value: &self._sender)
            case 2: try decoder.decodeSingularUInt64Field(value: &self._timestamp)
            default: break
            }
        }
    }

    func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
        if let v = self._sender {
            try visitor.visitSingularStringField(value: v, fieldNumber: 1)
        }
        if let v = self._timestamp {
            try visitor.visitSingularUInt64Field(value: v, fieldNumber: 2)
        }
        try self.unknownFields.traverse(visitor: &visitor)
    }

    func _protobuf_generated_isEqualTo(other: Signalservice_SyncMessage.Read) -> Bool {
        if self._sender != other._sender { return false }
        if self._timestamp != other._timestamp { return false }
        if self.unknownFields != other.unknownFields { return false }
        return true
    }
}

extension Signalservice_AttachmentPointer: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
    static let protoMessageName: String = _protobuf_package + ".AttachmentPointer"
    static let _protobuf_nameMap: SwiftProtobuf._NameMap = [
        1: .same(proto: "id"),
        2: .same(proto: "contentType"),
        3: .same(proto: "key"),
        4: .same(proto: "size"),
        5: .same(proto: "thumbnail"),
        6: .same(proto: "digest")
    ]

    mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
        while let fieldNumber = try decoder.nextFieldNumber() {
            switch fieldNumber {
            case 1: try decoder.decodeSingularFixed64Field(value: &self._id)
            case 2: try decoder.decodeSingularStringField(value: &self._contentType)
            case 3: try decoder.decodeSingularBytesField(value: &self._key)
            case 4: try decoder.decodeSingularUInt32Field(value: &self._size)
            case 5: try decoder.decodeSingularBytesField(value: &self._thumbnail)
            case 6: try decoder.decodeSingularBytesField(value: &self._digest)
            default: break
            }
        }
    }

    func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
        if let v = self._id {
            try visitor.visitSingularFixed64Field(value: v, fieldNumber: 1)
        }
        if let v = self._contentType {
            try visitor.visitSingularStringField(value: v, fieldNumber: 2)
        }
        if let v = self._key {
            try visitor.visitSingularBytesField(value: v, fieldNumber: 3)
        }
        if let v = self._size {
            try visitor.visitSingularUInt32Field(value: v, fieldNumber: 4)
        }
        if let v = self._thumbnail {
            try visitor.visitSingularBytesField(value: v, fieldNumber: 5)
        }
        if let v = self._digest {
            try visitor.visitSingularBytesField(value: v, fieldNumber: 6)
        }
        try self.unknownFields.traverse(visitor: &visitor)
    }

    func _protobuf_generated_isEqualTo(other: Signalservice_AttachmentPointer) -> Bool {
        if self._id != other._id { return false }
        if self._contentType != other._contentType { return false }
        if self._key != other._key { return false }
        if self._size != other._size { return false }
        if self._thumbnail != other._thumbnail { return false }
        if self._digest != other._digest { return false }
        if self.unknownFields != other.unknownFields { return false }
        return true
    }
}

extension Signalservice_GroupContext: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
    static let protoMessageName: String = _protobuf_package + ".GroupContext"
    static let _protobuf_nameMap: SwiftProtobuf._NameMap = [
        1: .same(proto: "id"),
        2: .same(proto: "type"),
        3: .same(proto: "name"),
        4: .same(proto: "members"),
        5: .same(proto: "avatar")
    ]

    fileprivate class _StorageClass {
        var _id: Data?
        var _type: Signalservice_GroupContext.TypeEnum?
        var _name: String?
        var _members: [String] = []
        var _avatar: Signalservice_AttachmentPointer?

        static let defaultInstance = _StorageClass()

        private init() {}

        init(copying source: _StorageClass) {
            self._id = source._id
            self._type = source._type
            self._name = source._name
            self._members = source._members
            self._avatar = source._avatar
        }
    }

    fileprivate mutating func _uniqueStorage() -> _StorageClass {
        if !isKnownUniquelyReferenced(&self._storage) {
            self._storage = _StorageClass(copying: self._storage)
        }
        return self._storage
    }

    mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
        _ = self._uniqueStorage()
        try withExtendedLifetime(self._storage) { (_storage: _StorageClass) in
            while let fieldNumber = try decoder.nextFieldNumber() {
                switch fieldNumber {
                case 1: try decoder.decodeSingularBytesField(value: &_storage._id)
                case 2: try decoder.decodeSingularEnumField(value: &_storage._type)
                case 3: try decoder.decodeSingularStringField(value: &_storage._name)
                case 4: try decoder.decodeRepeatedStringField(value: &_storage._members)
                case 5: try decoder.decodeSingularMessageField(value: &_storage._avatar)
                default: break
                }
            }
        }
    }

    func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
        try withExtendedLifetime(self._storage) { (_storage: _StorageClass) in
            if let v = _storage._id {
                try visitor.visitSingularBytesField(value: v, fieldNumber: 1)
            }
            if let v = _storage._type {
                try visitor.visitSingularEnumField(value: v, fieldNumber: 2)
            }
            if let v = _storage._name {
                try visitor.visitSingularStringField(value: v, fieldNumber: 3)
            }
            if !_storage._members.isEmpty {
                try visitor.visitRepeatedStringField(value: _storage._members, fieldNumber: 4)
            }
            if let v = _storage._avatar {
                try visitor.visitSingularMessageField(value: v, fieldNumber: 5)
            }
        }
        try self.unknownFields.traverse(visitor: &visitor)
    }

    func _protobuf_generated_isEqualTo(other: Signalservice_GroupContext) -> Bool {
        if self._storage !== other._storage {
            let storagesAreEqual: Bool = withExtendedLifetime((_storage, other._storage)) { (_args: (_StorageClass, _StorageClass)) in
                let _storage = _args.0
                let other_storage = _args.1
                if _storage._id != other_storage._id { return false }
                if _storage._type != other_storage._type { return false }
                if _storage._name != other_storage._name { return false }
                if _storage._members != other_storage._members { return false }
                if _storage._avatar != other_storage._avatar { return false }
                return true
            }
            if !storagesAreEqual { return false }
        }
        if self.unknownFields != other.unknownFields { return false }
        return true
    }
}

extension Signalservice_GroupContext.TypeEnum: SwiftProtobuf._ProtoNameProviding {
    static let _protobuf_nameMap: SwiftProtobuf._NameMap = [
        0: .same(proto: "UNKNOWN"),
        1: .same(proto: "UPDATE"),
        2: .same(proto: "DELIVER"),
        3: .same(proto: "QUIT"),
        4: .same(proto: "REQUEST_INFO")
    ]
}

extension Signalservice_ContactDetails: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
    static let protoMessageName: String = _protobuf_package + ".ContactDetails"
    static let _protobuf_nameMap: SwiftProtobuf._NameMap = [
        1: .same(proto: "number"),
        2: .same(proto: "name"),
        3: .same(proto: "avatar"),
        4: .same(proto: "color")
    ]

    fileprivate class _StorageClass {
        var _number: String?
        var _name: String?
        var _avatar: Signalservice_ContactDetails.Avatar?
        var _color: String?

        static let defaultInstance = _StorageClass()

        private init() {}

        init(copying source: _StorageClass) {
            self._number = source._number
            self._name = source._name
            self._avatar = source._avatar
            self._color = source._color
        }
    }

    fileprivate mutating func _uniqueStorage() -> _StorageClass {
        if !isKnownUniquelyReferenced(&self._storage) {
            self._storage = _StorageClass(copying: self._storage)
        }
        return self._storage
    }

    mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
        _ = self._uniqueStorage()
        try withExtendedLifetime(self._storage) { (_storage: _StorageClass) in
            while let fieldNumber = try decoder.nextFieldNumber() {
                switch fieldNumber {
                case 1: try decoder.decodeSingularStringField(value: &_storage._number)
                case 2: try decoder.decodeSingularStringField(value: &_storage._name)
                case 3: try decoder.decodeSingularMessageField(value: &_storage._avatar)
                case 4: try decoder.decodeSingularStringField(value: &_storage._color)
                default: break
                }
            }
        }
    }

    func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
        try withExtendedLifetime(self._storage) { (_storage: _StorageClass) in
            if let v = _storage._number {
                try visitor.visitSingularStringField(value: v, fieldNumber: 1)
            }
            if let v = _storage._name {
                try visitor.visitSingularStringField(value: v, fieldNumber: 2)
            }
            if let v = _storage._avatar {
                try visitor.visitSingularMessageField(value: v, fieldNumber: 3)
            }
            if let v = _storage._color {
                try visitor.visitSingularStringField(value: v, fieldNumber: 4)
            }
        }
        try self.unknownFields.traverse(visitor: &visitor)
    }

    func _protobuf_generated_isEqualTo(other: Signalservice_ContactDetails) -> Bool {
        if self._storage !== other._storage {
            let storagesAreEqual: Bool = withExtendedLifetime((_storage, other._storage)) { (_args: (_StorageClass, _StorageClass)) in
                let _storage = _args.0
                let other_storage = _args.1
                if _storage._number != other_storage._number { return false }
                if _storage._name != other_storage._name { return false }
                if _storage._avatar != other_storage._avatar { return false }
                if _storage._color != other_storage._color { return false }
                return true
            }
            if !storagesAreEqual { return false }
        }
        if self.unknownFields != other.unknownFields { return false }
        return true
    }
}

extension Signalservice_ContactDetails.Avatar: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
    static let protoMessageName: String = Signalservice_ContactDetails.protoMessageName + ".Avatar"
    static let _protobuf_nameMap: SwiftProtobuf._NameMap = [
        1: .same(proto: "contentType"),
        2: .same(proto: "length")
    ]

    mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
        while let fieldNumber = try decoder.nextFieldNumber() {
            switch fieldNumber {
            case 1: try decoder.decodeSingularStringField(value: &self._contentType)
            case 2: try decoder.decodeSingularUInt32Field(value: &self._length)
            default: break
            }
        }
    }

    func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
        if let v = self._contentType {
            try visitor.visitSingularStringField(value: v, fieldNumber: 1)
        }
        if let v = self._length {
            try visitor.visitSingularUInt32Field(value: v, fieldNumber: 2)
        }
        try self.unknownFields.traverse(visitor: &visitor)
    }

    func _protobuf_generated_isEqualTo(other: Signalservice_ContactDetails.Avatar) -> Bool {
        if self._contentType != other._contentType { return false }
        if self._length != other._length { return false }
        if self.unknownFields != other.unknownFields { return false }
        return true
    }
}

extension Signalservice_GroupDetails: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
    static let protoMessageName: String = _protobuf_package + ".GroupDetails"
    static let _protobuf_nameMap: SwiftProtobuf._NameMap = [
        1: .same(proto: "id"),
        2: .same(proto: "name"),
        3: .same(proto: "members"),
        4: .same(proto: "avatar"),
        5: .same(proto: "active")
    ]

    fileprivate class _StorageClass {
        var _id: Data?
        var _name: String?
        var _members: [String] = []
        var _avatar: Signalservice_GroupDetails.Avatar?
        var _active: Bool?

        static let defaultInstance = _StorageClass()

        private init() {}

        init(copying source: _StorageClass) {
            self._id = source._id
            self._name = source._name
            self._members = source._members
            self._avatar = source._avatar
            self._active = source._active
        }
    }

    fileprivate mutating func _uniqueStorage() -> _StorageClass {
        if !isKnownUniquelyReferenced(&self._storage) {
            self._storage = _StorageClass(copying: self._storage)
        }
        return self._storage
    }

    mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
        _ = self._uniqueStorage()
        try withExtendedLifetime(self._storage) { (_storage: _StorageClass) in
            while let fieldNumber = try decoder.nextFieldNumber() {
                switch fieldNumber {
                case 1: try decoder.decodeSingularBytesField(value: &_storage._id)
                case 2: try decoder.decodeSingularStringField(value: &_storage._name)
                case 3: try decoder.decodeRepeatedStringField(value: &_storage._members)
                case 4: try decoder.decodeSingularMessageField(value: &_storage._avatar)
                case 5: try decoder.decodeSingularBoolField(value: &_storage._active)
                default: break
                }
            }
        }
    }

    func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
        try withExtendedLifetime(self._storage) { (_storage: _StorageClass) in
            if let v = _storage._id {
                try visitor.visitSingularBytesField(value: v, fieldNumber: 1)
            }
            if let v = _storage._name {
                try visitor.visitSingularStringField(value: v, fieldNumber: 2)
            }
            if !_storage._members.isEmpty {
                try visitor.visitRepeatedStringField(value: _storage._members, fieldNumber: 3)
            }
            if let v = _storage._avatar {
                try visitor.visitSingularMessageField(value: v, fieldNumber: 4)
            }
            if let v = _storage._active {
                try visitor.visitSingularBoolField(value: v, fieldNumber: 5)
            }
        }
        try self.unknownFields.traverse(visitor: &visitor)
    }

    func _protobuf_generated_isEqualTo(other: Signalservice_GroupDetails) -> Bool {
        if self._storage !== other._storage {
            let storagesAreEqual: Bool = withExtendedLifetime((_storage, other._storage)) { (_args: (_StorageClass, _StorageClass)) in
                let _storage = _args.0
                let other_storage = _args.1
                if _storage._id != other_storage._id { return false }
                if _storage._name != other_storage._name { return false }
                if _storage._members != other_storage._members { return false }
                if _storage._avatar != other_storage._avatar { return false }
                if _storage._active != other_storage._active { return false }
                return true
            }
            if !storagesAreEqual { return false }
        }
        if self.unknownFields != other.unknownFields { return false }
        return true
    }
}

extension Signalservice_GroupDetails.Avatar: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
    static let protoMessageName: String = Signalservice_GroupDetails.protoMessageName + ".Avatar"
    static let _protobuf_nameMap: SwiftProtobuf._NameMap = [
        1: .same(proto: "contentType"),
        2: .same(proto: "length")
    ]

    mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
        while let fieldNumber = try decoder.nextFieldNumber() {
            switch fieldNumber {
            case 1: try decoder.decodeSingularStringField(value: &self._contentType)
            case 2: try decoder.decodeSingularUInt32Field(value: &self._length)
            default: break
            }
        }
    }

    func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
        if let v = self._contentType {
            try visitor.visitSingularStringField(value: v, fieldNumber: 1)
        }
        if let v = self._length {
            try visitor.visitSingularUInt32Field(value: v, fieldNumber: 2)
        }
        try self.unknownFields.traverse(visitor: &visitor)
    }

    func _protobuf_generated_isEqualTo(other: Signalservice_GroupDetails.Avatar) -> Bool {
        if self._contentType != other._contentType { return false }
        if self._length != other._length { return false }
        if self.unknownFields != other.unknownFields { return false }
        return true
    }
}
